"""
backend/alembic/script.py.mako — Alembic Migration Script Template
====================================================================
This template is used by `alembic revision` to generate new migration files.
"""
"""create_all_tables_phase7

Revision ID: 6b3471609ae9
Revises: 
Create Date: 2026-07-26 15:55:23.036434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3471609ae9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_rates',
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('gold_24k', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('gold_22k', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('silver', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('rate_date')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('businesses',
    sa.Column('business_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_businesses_business_id'), 'businesses', ['business_id'], unique=False)
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('metal', sa.String(length=50), nullable=False),
    sa.Column('purity', sa.String(length=50), nullable=False),
    sa.Column('gross_weight', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('net_weight', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('business_id', 'sku', name='uq_products_business_sku')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('purchases',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('metal_rate', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('metal_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('making_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchases_business_id'), 'purchases', ['business_id'], unique=False)
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_id'), 'purchases', ['purchase_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('selling_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('making_charge', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('cost_basis', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_business_id'), 'sales', ['business_id'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_business_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_purchases_purchase_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_business_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('metal_rates')
    # ### end Alembic commands ###
